trainingInput:
  scaleTier: STANDARD_1
  hyperparameters:
    goal: MAXIMIZE
    hyperparameterMetricTag: accuracy
    maxTrials: 4
    maxParallelTrials: 3
    params:
    - parameterName: batchsize
      type: INTEGER
      minValue: 16
      maxValue: 512
      scaleType: UNIT_LOG_SCALE
    - parameterName: feat_eng_cols
      type: INTEGER
      minValue: 0
      maxValue: 1
      scaleType: UNIT_LINEAR_SCALE