trainingInput:
  scaleTier: STANDARD_1
  hyperparameters:
    goal: MINIMIZE
    hyperparameterMetricTag: loss
    maxTrials: 4
    maxParallelTrials: 3
    params:
    - parameterName: feat_eng_cols
      type: INTEGER
      minValue: 0
      maxValue: 1
      scaleType: UNIT_LINEAR_SCALE